runtime: nodejs
env: flex
service: photoverifyapp

manual_scaling:
  instances : 1

handlers:
  - url: /index.html
    static_files: public/index.html
    upload: public/index.html
  - url: /
    static_dir: public/