runtime: nodejs
env: flex
service: photoverifyapp

manual_scaling:
  instances : 1

handlers:
  - url: /index.html
    static_files: client/index.html
    upload: client/index.html
  - url: /
    static_dir: client/